# Generated by Django 4.1.5 on 2023-01-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='loaction',
            new_name='location',
        ),
    ]
