# Generated by Django 4.1.5 on 2023-01-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_loaction_settings_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='location',
            field=models.TextField(max_length=500),
        ),
    ]
